version: '3.6'
services:
  server:
    image: farmrone/plutus-playground:latest
    command:
      - nix-shell
      - --run
      - 'cd plutus-playground-client && plutus-playground-server'    
    restart: always
    ports:
      - '8080:8080'
  client:
    image: farmrone/plutus-playground:latest
    command:
      - nix-shell
      - --run
      - 'cd plutus-playground-client && npm run start'    
    depends_on:
      - server
    restart: always
    ports:
      - '8009:8009'
    links:
      - server
